### ISSUE TITLE
AccessControlManager: set owner address in constructor

### ISSUE THREAD

**Issue by pcppcp** [AnyLedger/smart-contracts#6]
`owner` variable shouldn't be hardcoded

owner check should also use modifier instead of test in the function

**Comment by sameepsi** [comment]
Open-zeppelin's **Ownable** contract should be used.
But the test to check owner address in the **hasAccess** method is correct and should not be replaced by the modifier.
Modifiers are basically used to control behaviour of the function like restricting who can access the method, unlocking functions at the certain time fram. But in our if owner address calls the **hasAccess** method we return **true** otherwise we check for permission.
But in nutshell anybody could access the function and get the return value.

**Comment by lorepieri8** [comment]
Solved by #8
